### ISSUE TITLE
element.replace is not a function

### ISSUE THREAD

**Issue by tiagosiebler** [aichbauer/node-convert-array-to-csv#16]
```
/path/to/project/node_modules/convert-array-to-csv/lib/helpers/append-element.js:15
  var thisElement = element.replace(/"/g, '""');
                            ^

TypeError: element.replace is not a function
    at escapeDoubleQuotesInsideElement (/path/to/project/node_modules/convert-array-to-csv/lib/helpers/append-element.js:15:29)
    at appendElement (/path/to/project/node_modules/convert-array-to-csv/lib/helpers/append-element.js:24:19)
    at /path/to/project/node_modules/convert-array-to-csv/lib/modules/convert-array-of-objects-to-csv.js:45:47
    at Array.forEach (<anonymous>)
    at /path/to/project/node_modules/convert-array-to-csv/lib/modules/convert-array-of-objects-to-csv.js:43:13
    at Array.forEach (<anonymous>)
    at convertArrayOfObjectsToCSV (/path/to/project/node_modules/convert-array-to-csv/lib/modules/convert-array-of-objects-to-csv.js:33:9)
    at convertArrayToCSV (/path/to/project/node_modules/convert-array-to-csv/lib/index.js:29:69)
```

Example array tested with:
```
[{"symbols":"someSymbol","intervals":"1d","strategy":"ts_random","finalBalance":1113.2064033692236,"vsHold":4.1,"profitPercent":11.321,"totalTrades":20,"tradesPerDay":0.22222,"daysTested":90},{"symbols":"someSymbol","intervals":"12h","strategy":"ts_random","finalBalance":910.3135744368446,"vsHold":-15.54,"profitPercent":-8.969,"totalTrades":38,"tradesPerDay":0.42222,"daysTested":90},{"symbols":"someSymbol","intervals":"8h","strategy":"ts_random","finalBalance":822.2188567882868,"vsHold":-21.76,"profitPercent":-17.778,"totalTrades":69,"tradesPerDay":0.76667,"daysTested":90}]
```

```
  const { convertArrayToCSV } = require('convert-array-to-csv');
  const csvData = convertArrayToCSV(tabularResults);
```

**Comment by aichbauer** [comment]
@tiagosiebler I will take a look into that as soon as possible...

**Comment by aichbauer** [comment]
@tiagosiebler v1.0.7 should fix it for your use case

**Comment by tiagosiebler** [comment]
Thanks!
